// Script updates locations with listed properties, adds a location if it doesn't exist in the db

const MongoClient = require('mongodb').MongoClient;

async function main() {
	/**
   * Connection URI. Update <userloc>, <password>, and <your-cluster-url> to reflect your cluster.
   * See https://docs.mongodb.com/ecosystem/drivers/node/ for more details
   */

	const uri = 'mongodb+srv://turqbot:turquoise2007@turqdb-30xsx.gcp.mongodb.net/turqdb?retryWrites=true&w=majority';
	const client = new MongoClient(uri, { useNewUrlParser: true, useUnifiedTopology: true });

	try {
		// Connect to the MongoDB cluster
		await client.connect();

		await updatelocation(client,
			{
				loc: 'Leddin Town',
				simpLoc: 'leddintown',
				altSimpLoc: '',
				Areas: '',
				island: 'Brol Island',
				flyable: true,
				surfable: false,
				fishable: false,
				divable: false,
				gym: false,
				rival: true,
				sidequests: false,
				revHQ: false,
				numRequiredJobs: 0,
				numRequiredBadges: 0,
				ferry: true,
				accessTo: ['routenl1_south', 'routenl20'],
				wilds: false,
				trainers: true,
				weather: '',
				wthrChance: 0,
				shops: ['PokéMart'],
			},
		);

		await updatelocation(client,
			{
				loc: 'Route NL1 South',
				simpLoc: 'routenl1',
				altSimpLoc: '',
				simpArea: 'south',
				island: 'Brol Island',
				flyable: true,
				surfable: false,
				fishable: false,
				divable: false,
				gym: false,
				rival: false,
				sidequests: false,
				revHQ: false,
				numRequiredJobs: 0,
				numRequiredBadges: 0,
				ferry: false,
				accessTo: ['leddintown', 'dingbatcave_uppercaverns'],
				wilds: true,
				trainers: true,
				weather: '',
				wthrChance: 0,
				shops: [],
			},
		);

		await updatelocation(client,
			{
				loc: 'Dingbat Cave Upper Caverns',
				simpLoc: 'dingbatcave',
				altSimpLoc: '',
				simpArea: 'uppercaverns',
				island: 'Brol Island',
				flyable: true,
				surfable: false,
				fishable: false,
				divable: false,
				gym: false,
				rival: false,
				sidequests: true,
				revHQ: false,
				numRequiredJobs: 0,
				numRequiredBadges: 0,
				ferry: false,
				accessTo: ['routenl1_south', 'routenl1_north'],
				wilds: true,
				trainers: true,
				weather: '',
				wthrChance: 0,
				shops: [],
			},
		);

		await updatelocation(client,
			{
				loc: 'Dingbat Cave Lower Caverns',
				simpLoc: 'dingbatcave',
				altSimpLoc: '',
				simpArea: 'lowercaverns',
				island: 'Brol Island',
				flyable: false,
				surfable: false,
				fishable: false,
				divable: false,
				gym: false,
				rival: false,
				sidequests: true,
				revHQ: false,
				numRequiredJobs: 0,
				numRequiredBadges: 3,
				ferry: false,
				accessTo: ['dingbatcave_uppercaverns'],
				wilds: true,
				trainers: true,
				weather: '',
				wthrChance: 0,
				shops: [],
			},
		);

		await updatelocation(client,
			{
				loc: 'Route NL1 North',
				simpLoc: 'routenl1',
				altSimpLoc: '',
				simpArea: 'north',
				island: 'Brol Island',
				flyable: true,
				surfable: false,
				fishable: false,
				divable: false,
				gym: false,
				rival: false,
				sidequests: false,
				revHQ: false,
				numRequiredJobs: 0,
				numRequiredBadges: 0,
				ferry: false,
				accessTo: ['dingbatcave', 'shrdlutown'],
				wilds: true,
				trainers: true,
				weather: '',
				wthrChance: 0,
				shops: [],
			},
		);

		await updatelocation(client,
			{
				loc: 'Shrdlu Town',
				simpLoc: 'shrdlutown',
				altSimpLoc: '',
				simpArea: '',
				island: 'Brol Island',
				flyable: true,
				surfable: false,
				fishable: false,
				divable: false,
				gym: false,
				rival: false,
				sidequests: true,
				revHQ: false,
				numRequiredJobs: 0,
				numRequiredBadges: 0,
				ferry: true,
				accessTo: ['routenl1_north', 'routenl2'],
				wilds: false,
				trainers: true,
				weather: '',
				wthrChance: 0,
				shops: ['PokéMart'],
			},
		);

		await updatelocation(client,
			{
				loc: 'Route NL2',
				simpLoc: 'routenl2',
				altSimpLoc: '',
				simpArea: '',
				island: '',
				flyable: true,
				surfable: true,
				fishable: true,
				divable: true,
				gym: false,
				rival: false,
				sidequests: false,
				revHQ: false,
				numRequiredJobs: 0,
				numRequiredBadges: 0,
				ferry: false,
				accessTo: ['shrdlutown', 'allogracity'],
				wilds: true,
				trainers: true,
				weather: '',
				wthrChance: 0,
				shops: [],
			},
		);

		await updatelocation(client,
			{
				loc: 'Allogra City',
				simpLoc: 'allogracity',
				altSimpLoc: '',
				simpArea: '',
				island: 'Kronea Island',
				flyable: true,
				surfable: false,
				fishable: false,
				divable: false,
				gym: true,
				rival: false,
				sidequests: true,
				revHQ: false,
				numRequiredJobs: 0,
				numRequiredBadges: 0,
				ferry: true,
				accessTo: ['routenl2', 'routenl3'],
				wilds: false,
				trainers: true,
				weather: '',
				wthrChance: 0,
				shops: ['PokéMart'],
			},
		);

		await updatelocation(client,
			{
				loc: 'Route NL3',
				simpLoc: 'routenl3',
				altSimpLoc: '',
				simpArea: '',
				island: 'Kronea Island',
				flyable: true,
				surfable: false,
				fishable: true,
				divable: false,
				gym: false,
				rival: false,
				sidequests: true,
				revHQ: false,
				numRequiredJobs: 0,
				numRequiredBadges: 0,
				ferry: false,
				accessTo: ['routenl2', 'routenl3'],
				wilds: true,
				trainers: true,
				weather: '',
				wthrChance: 0,
				shops: [],
			},
		);

		await updatelocation(client,
			{
				loc: 'Denath Village',
				simpLoc: 'denathvillage',
				altSimpLoc: '',
				simpArea: '',
				island: 'Kronea Island',
				flyable: true,
				surfable: false,
				fishable: false,
				divable: false,
				gym: true,
				rival: true,
				sidequests: false,
				revHQ: true,
				numRequiredJobs: 0,
				numRequiredBadges: 0,
				ferry: false,
				accessTo: ['routenl3', 'routenl4/denathplains'],
				wilds: false,
				trainers: true,
				weather: '',
				wthrChance: 0,
				shops: ['PokéMart', 'Open-Air Market'],
			},
		);

		await updatelocation(client,
			{
				loc: 'Route NL4 / Denath Plains',
				simpLoc: 'routenl4',
				altSimpLoc: 'denathplains',
				simpArea: '',
				island: 'Kronea Island',
				flyable: true,
				surfable: false,
				fishable: false,
				divable: false,
				gym: false,
				rival: false,
				sidequests: true,
				revHQ: false,
				numRequiredJobs: 0,
				numRequiredBadges: 0,
				ferry: false,
				accessTo: ['denathvillage', 'ambalchitemple_gardens', 'routenl5'],
				wilds: true,
				trainers: true,
				weather: '',
				wthrChance: 0,
				shops: [],
			},
		);

		await updatelocation(client,
			{
				loc: 'Ambalchi Temple Gardens',
				simpLoc: 'ambalchitemple',
				altSimpLoc: '',
				simpArea: 'gardens',
				island: 'Kronea Island',
				flyable: true,
				surfable: false,
				fishable: false,
				divable: false,
				gym: false,
				rival: false,
				sidequests: false,
				revHQ: false,
				numRequiredJobs: 0,
				numRequiredBadges: 0,
				ferry: false,
				accessTo: ['routenl4/denathplains', 'ambalchitemple_ruins'],
				wilds: true,
				trainers: true,
				weather: '',
				wthrChance: 0,
				shops: [],
			},
		);

		await updatelocation(client,
			{
				loc: 'Ambalchi Temple Ruins',
				simpLoc: 'ambalchitemple',
				altSimpLoc: '',
				simpArea: 'ruins',
				island: 'Kronea Island',
				flyable: true,
				surfable: false,
				fishable: false,
				divable: false,
				gym: false,
				rival: false,
				sidequests: false,
				revHQ: false,
				numRequiredJobs: 2,
				numRequiredBadges: 3,
				ferry: false,
				accessTo: ['ambalchitemple_gardens', 'ambalchitemple_shrine'],
				wilds: true,
				trainers: true,
				weather: '',
				wthrChance: 0,
				shops: [],
			},
		);

		await updatelocation(client,
			{
				loc: 'Ambalchi Temple Shrine',
				simpLoc: 'ambalchitemple',
				altSimpLoc: '',
				simpArea: 'shrine',
				island: 'Kronea Island',
				flyable: false,
				surfable: false,
				fishable: false,
				divable: false,
				gym: false,
				rival: false,
				sidequests: false,
				revHQ: false,
				numRequiredJobs: 6,
				numRequiredBadges: 5,
				ferry: false,
				accessTo: ['ambalchitemple_ruins'],
				wilds: true,
				trainers: false,
				weather: '',
				wthrChance: 0,
				shops: [],
			},
		);

		await updatelocation(client,
			{
				loc: 'Route NL5',
				simpLoc: 'routenl5',
				altSimpLoc: '',
				simpArea: '',
				island: 'Kronea Island',
				flyable: true,
				surfable: false,
				fishable: false,
				divable: false,
				gym: false,
				rival: false,
				sidequests: true,
				revHQ: false,
				numRequiredJobs: 0,
				numRequiredBadges: 0,
				ferry: true,
				accessTo: ['routenl4/denathplains', 'routenl6'],
				wilds: true,
				trainers: true,
				weather: '',
				wthrChance: 0,
				shops: [],
			},
		);

		await updatelocation(client,
			{
				loc: 'Route NL6',
				simpLoc: 'routenl6',
				altSimpLoc: '',
				simpArea: '',
				island: '',
				flyable: true,
				surfable: true,
				fishable: true,
				divable: true,
				gym: false,
				rival: false,
				sidequests: false,
				revHQ: false,
				numRequiredJobs: 0,
				numRequiredBadges: 0,
				ferry: false,
				accessTo: ['routenl5', 'routenl7'],
				wilds: true,
				trainers: true,
				weather: '',
				wthrChance: 0,
				shops: [],
			},
		);

		await updatelocation(client,
			{
				loc: 'Route NL7',
				simpLoc: 'routenl7',
				altSimpLoc: '',
				simpArea: '',
				island: 'Tilnen Island',
				flyable: true,
				surfable: false,
				fishable: false,
				divable: false,
				gym: false,
				rival: false,
				sidequests: false,
				revHQ: false,
				numRequiredJobs: 0,
				numRequiredBadges: 0,
				ferry: true,
				accessTo: ['routenl6', 'szlazancity'],
				wilds: true,
				trainers: true,
				weather: '',
				wthrChance: 0,
				shops: [],
			},
		);

		await updatelocation(client,
			{
				loc: 'Szlazan City',
				simpLoc: 'szlazancity',
				altSimpLoc: '',
				simpArea: '',
				island: 'Tilnen Island',
				flyable: true,
				surfable: false,
				fishable: false,
				divable: false,
				gym: true,
				rival: true,
				sidequests: true,
				revHQ: true,
				numRequiredJobs: 0,
				numRequiredBadges: 0,
				ferry: false,
				accessTo: ['routenl7', 'acoatyltower_lowerfloors', 'routenl8'],
				wilds: false,
				trainers: true,
				weather: '',
				wthrChance: 0,
				shops: ['PokéMart'],
			},
		);

		await updatelocation(client,
			{
				loc: 'Acoatyl Tower Lower Floors',
				simpLoc: 'acoatyltower',
				altSimpLoc: '',
				simpArea: 'lowerfloors',
				island: 'Tilnen Island',
				flyable: true,
				surfable: false,
				fishable: false,
				divable: false,
				gym: false,
				rival: false,
				sidequests: false,
				revHQ: false,
				numRequiredJobs: 0,
				numRequiredBadges: 0,
				ferry: false,
				accessTo: ['szlazancity', 'acoatyltower_upperfloors'],
				wilds: true,
				trainers: true,
				weather: '',
				wthrChance: 0,
				shops: [],
			},
		);

		await updatelocation(client,
			{
				loc: 'Acoatyl Tower Upper Floors',
				simpLoc: 'acoatyltower',
				altSimpLoc: '',
				simpArea: 'upperfloors',
				island: 'Tilnen Island',
				flyable: false,
				surfable: false,
				fishable: false,
				divable: false,
				gym: false,
				rival: false,
				sidequests: false,
				revHQ: false,
				numRequiredJobs: 2,
				numRequiredBadges: 3,
				ferry: false,
				accessTo: ['acoatyltower_lowerfloors', 'acoatyltower_shrine'],
				wilds: true,
				trainers: true,
				weather: '',
				wthrChance: 0,
				shops: [],
			},
		);

		await updatelocation(client,
			{
				loc: 'Acoatyl Tower Shrine',
				simpLoc: 'acoatyltower',
				altSimpLoc: '',
				simpArea: 'shrine',
				island: 'Tilnen Island',
				flyable: false,
				surfable: false,
				fishable: false,
				divable: false,
				gym: false,
				rival: false,
				sidequests: false,
				revHQ: false,
				numRequiredJobs: 6,
				numRequiredBadges: 5,
				ferry: false,
				accessTo: ['acoatyltower_lowerfloors', 'acoatyltower_shrine'],
				wilds: true,
				trainers: false,
				weather: '',
				wthrChance: 0,
				shops: [],
			},
		);

		await updatelocation(client,
			{
				loc: 'Route NL8',
				simpLoc: 'routenl8',
				altSimpLoc: '',
				simpArea: '',
				island: 'Tilnen Island',
				flyable: true,
				surfable: false,
				fishable: false,
				divable: false,
				gym: false,
				rival: false,
				sidequests: false,
				revHQ: false,
				numRequiredJobs: 0,
				numRequiredBadges: 0,
				ferry: false,
				accessTo: ['szlazancity', 'baaresatown'],
				wilds: true,
				trainers: true,
				weather: 'Rain',
				wthrChance: 25,
				shops: [],
			},
		);

		await updatelocation(client,
			{
				loc: 'Baaresa Town',
				simpLoc: 'baaresatown',
				altSimpLoc: '',
				simpArea: '',
				island: 'Tilnen Island',
				flyable: true,
				surfable: false,
				fishable: false,
				divable: false,
				gym: true,
				rival: false,
				sidequests: false,
				revHQ: true,
				numRequiredJobs: 0,
				numRequiredBadges: 0,
				ferry: false,
				accessTo: ['routenl8', 'fulgurokmountains'],
				wilds: true,
				trainers: true,
				weather: 'Rain',
				wthrChance: 25,
				shops: ['PokéMart'],
			},
		);

		await updatelocation(client,
			{
				loc: 'Fulgurok Mountains Mountainside',
				simpLoc: 'fulgurokmountains',
				altSimpLoc: '',
				simpArea: 'mountainside',
				island: 'Tilnen Island',
				flyable: true,
				surfable: false,
				fishable: false,
				divable: false,
				gym: false,
				rival: false,
				sidequests: false,
				revHQ: false,
				numRequiredJobs: 0,
				numRequiredBadges: 0,
				ferry: false,
				accessTo: ['baaresatown', 'fulgurokmountains_caves', 'fulgurokmountains_lowpeaks', 'routenl9'],
				wilds: true,
				trainers: true,
				weather: 'Rain',
				wthrChance: 50,
				shops: [],
			},
		);

		await updatelocation(client,
			{
				loc: 'Fulgurok Mountains Caves',
				simpLoc: 'fulgurokmountains',
				altSimpLoc: '',
				simpArea: 'caves',
				island: 'Tilnen Island',
				flyable: true,
				surfable: false,
				fishable: false,
				divable: false,
				gym: false,
				rival: false,
				sidequests: false,
				revHQ: false,
				numRequiredJobs: 2,
				numRequiredBadges: 3,
				ferry: false,
				accessTo: ['fulgurokmountains_mountainside', 'fulgurokmountains_shrine'],
				wilds: true,
				trainers: true,
				weather: '',
				wthrChance: 0,
				shops: [],
			},
		);

		await updatelocation(client,
			{
				loc: 'Fulgurok Mountains Shrine',
				simpLoc: 'fulgurokmountains',
				altSimpLoc: '',
				simpArea: 'shrine',
				island: 'Tilnen Island',
				flyable: false,
				surfable: false,
				fishable: false,
				divable: false,
				gym: false,
				rival: false,
				sidequests: false,
				revHQ: false,
				numRequiredJobs: 6,
				numRequiredBadges: 5,
				ferry: false,
				accessTo: ['fulgurokmountains_caves'],
				wilds: true,
				trainers: false,
				weather: '',
				wthrChance: 0,
				shops: [],
			},
		);

		await updatelocation(client,
			{
				loc: 'Fulgurok Mountains Low Peaks',
				simpLoc: 'fulgurokmountains',
				altSimpLoc: '',
				simpArea: 'lowpeaks',
				island: 'Tilnen Island',
				flyable: false,
				surfable: false,
				fishable: false,
				divable: false,
				gym: false,
				rival: false,
				sidequests: true,
				revHQ: false,
				numRequiredJobs: 0,
				numRequiredBadges: 0,
				ferry: false,
				accessTo: ['fulgurokmountains_mountainside'],
				wilds: true,
				trainers: true,
				weather: 'Hail',
				wthrChance: 50,
				shops: [],
			},
		);

		await updatelocation(client,
			{
				loc: 'Route NL9',
				simpLoc: 'routenl9',
				altSimpLoc: '',
				simpArea: '',
				island: 'Tilnen Island',
				flyable: true,
				surfable: false,
				fishable: false,
				divable: false,
				gym: false,
				rival: false,
				sidequests: true,
				revHQ: false,
				numRequiredJobs: 0,
				numRequiredBadges: 0,
				ferry: false,
				accessTo: ['fulgurokmountains_mountainside', 'fulgurokcaves', 'routenl10'],
				wilds: true,
				trainers: true,
				weather: 'Fog',
				wthrChance: 100,
				shops: [],
			},
		);

		await updatelocation(client,
			{
				loc: 'Fulgurok Caves',
				simpLoc: 'fulgurokcaves',
				altSimpLoc: '',
				simpArea: '',
				island: 'Tilnen Island',
				flyable: true,
				surfable: false,
				fishable: false,
				divable: false,
				gym: false,
				rival: false,
				sidequests: false,
				revHQ: false,
				numRequiredJobs: 0,
				numRequiredBadges: 0,
				ferry: false,
				accessTo: ['routenl9', 'routenl10', 'fulgurokisland'],
				wilds: true,
				trainers: true,
				weather: '',
				wthrChance: 0,
				shops: [],
			},
		);

		await updatelocation(client,
			{
				loc: 'Fulgurok Island',
				simpLoc: 'fulgurokisland',
				altSimpLoc: '',
				simpArea: '',
				island: 'Tilnen Island',
				flyable: true,
				surfable: false,
				fishable: false,
				divable: false,
				gym: false,
				rival: false,
				sidequests: true,
				revHQ: false,
				numRequiredJobs: 0,
				numRequiredBadges: 0,
				ferry: false,
				accessTo: ['fulgurokcaves'],
				wilds: true,
				trainers: true,
				weather: '',
				wthrChance: 0,
				shops: [],
			},
		);

		await updatelocation(client,
			{
				loc: 'Route NL10',
				simpLoc: 'routenl10',
				altSimpLoc: '',
				simpArea: '',
				island: 'Tilnen Island',
				flyable: true,
				surfable: false,
				fishable: false,
				divable: false,
				gym: false,
				rival: false,
				sidequests: false,
				revHQ: false,
				numRequiredJobs: 0,
				numRequiredBadges: 0,
				ferry: false,
				accessTo: ['routenl9', 'fulgurokcaves', 'diacity'],
				wilds: true,
				trainers: true,
				weather: '',
				wthrChance: 0,
				shops: [],
			},
		);

		await updatelocation(client,
			{
				loc: 'Dia City',
				simpLoc: 'diacity',
				altSimpLoc: '',
				simpArea: '',
				island: 'Tilnen Island',
				flyable: true,
				surfable: false,
				fishable: false,
				divable: false,
				gym: false,
				rival: true,
				sidequests: false,
				revHQ: false,
				numRequiredJobs: 0,
				numRequiredBadges: 0,
				ferry: true,
				accessTo: ['routenl10', 'routenl11'],
				wilds: false,
				trainers: true,
				weather: '',
				wthrChance: 0,
				shops: ['PokéMart', 'Dia Department Store', 'Fabulous Items \'R\' Us'],
			},
		);

		await updatelocation(client,
			{
				loc: 'Route NL11',
				simpLoc: 'routenl11',
				altSimpLoc: '',
				simpArea: '',
				island: '',
				flyable: true,
				surfable: true,
				fishable: true,
				divable: true,
				gym: false,
				rival: false,
				sidequests: false,
				revHQ: false,
				numRequiredJobs: 0,
				numRequiredBadges: 0,
				ferry: true,
				accessTo: ['diacity', 'routenl12/falantrdocks'],
				wilds: true,
				trainers: true,
				weather: '',
				wthrChance: 0,
				shops: [],
			},
		);

		await updatelocation(client,
			{
				loc: 'Route NL12 / Falantr Docks',
				simpLoc: 'routenl12',
				altSimpLoc: 'falantrdocks',
				simpArea: '',
				island: 'Xybryle Island',
				flyable: true,
				surfable: false,
				fishable: false,
				divable: false,
				gym: false,
				rival: false,
				sidequests: true,
				revHQ: false,
				numRequiredJobs: 0,
				numRequiredBadges: 0,
				ferry: true,
				accessTo: ['routenl11', 'falantrcity', 'routenl21'],
				wilds: true,
				trainers: true,
				weather: '',
				wthrChance: 0,
				shops: [],
			},
		);

		await updatelocation(client,
			{
				loc: 'Falantr City',
				simpLoc: 'falantrcity',
				altSimpLoc: '',
				simpArea: '',
				island: 'Xybryle Island',
				flyable: true,
				surfable: false,
				fishable: false,
				divable: false,
				gym: true,
				rival: false,
				sidequests: false,
				revHQ: false,
				numRequiredJobs: 0,
				numRequiredBadges: 0,
				ferry: false,
				accessTo: ['routenl12/falantrdocks', 'routenl13/xybrylebridge'],
				wilds: false,
				trainers: true,
				weather: '',
				wthrChance: 0,
				shops: ['PokéMart'],
			},
		);

		await updatelocation(client,
			{
				loc: 'Route NL13 / Xybryle Bridge',
				simpLoc: 'routenl13',
				altSimpLoc: 'xybrylebridge',
				simpArea: '',
				island: 'Xybryle Island',
				flyable: true,
				surfable: false,
				fishable: false,
				divable: false,
				gym: false,
				rival: false,
				sidequests: true,
				revHQ: false,
				numRequiredJobs: 0,
				numRequiredBadges: 0,
				ferry: false,
				accessTo: ['falantrcity', 'routenl14'],
				wilds: true,
				trainers: true,
				weather: '',
				wthrChance: 0,
				shops: [],
			},
		);

		await updatelocation(client,
			{
				loc: 'Route NL14',
				simpLoc: 'routenl14',
				altSimpLoc: '',
				simpArea: '',
				island: 'Xybryle Island',
				flyable: true,
				surfable: false,
				fishable: false,
				divable: false,
				gym: false,
				rival: false,
				sidequests: false,
				revHQ: false,
				numRequiredJobs: 0,
				numRequiredBadges: 0,
				ferry: true,
				accessTo: ['routenl13/xybrylebridge', 'runecity', 'routenl15'],
				wilds: true,
				trainers: true,
				weather: '',
				wthrChance: 0,
				shops: [],
			},
		);

		await updatelocation(client,
			{
				loc: 'Rune City',
				simpLoc: 'runecity',
				altSimpLoc: '',
				simpArea: '',
				island: 'Xybryle Island',
				flyable: true,
				surfable: false,
				fishable: false,
				divable: false,
				gym: true,
				rival: true,
				sidequests: true,
				revHQ: true,
				numRequiredJobs: 0,
				numRequiredBadges: 0,
				ferry: true,
				accessTo: ['routenl14', 'xybrylebay'],
				wilds: false,
				trainers: true,
				weather: '',
				wthrChance: 0,
				shops: ['PokéMart'],
			},
		);

		await updatelocation(client,
			{
				loc: 'Xybryle Bay',
				simpLoc: 'xybrylebay',
				altSimpLoc: '',
				simpArea: '',
				island: 'Xybryle Island',
				flyable: true,
				surfable: true,
				fishable: true,
				divable: true,
				gym: false,
				rival: false,
				sidequests: false,
				revHQ: false,
				numRequiredJobs: 0,
				numRequiredBadges: 0,
				ferry: false,
				accessTo: ['runecity', 'submarinesafari', 'ton-kura_seabed'],
				wilds: true,
				trainers: true,
				weather: '',
				wthrChance: 0,
				shops: [],
			},
		);

		await updatelocation(client,
			{
				loc: 'Submarine Safari',
				simpLoc: 'submarinesafari',
				altSimpLoc: '',
				simpArea: '',
				island: 'Xybryle Island',
				flyable: true,
				surfable: false,
				fishable: false,
				divable: true,
				gym: false,
				rival: false,
				sidequests: false,
				revHQ: false,
				numRequiredJobs: 0,
				numRequiredBadges: 0,
				ferry: false,
				accessTo: ['xybrylebay'],
				wilds: true,
				trainers: false,
				weather: 'Underwater',
				wthrChance: 100,
				shops: [],
			},
		);

		await updatelocation(client,
			{
				loc: 'Ton-Kura Seabed',
				simpLoc: 'ton-kura',
				altSimpLoc: '',
				simpArea: 'seabed',
				island: 'Xybryle Island',
				flyable: true,
				surfable: false,
				fishable: false,
				divable: true,
				gym: false,
				rival: false,
				sidequests: false,
				revHQ: false,
				numRequiredJobs: 0,
				numRequiredBadges: 0,
				ferry: false,
				accessTo: ['xybrylebay', 'ton-kura_caves'],
				wilds: true,
				trainers: true,
				weather: 'Underwater',
				wthrChance: 100,
				shops: [],
			},
		);

		await updatelocation(client,
			{
				loc: 'Ton-Kura Caves',
				simpLoc: 'ton-kura',
				altSimpLoc: '',
				simpArea: 'caves',
				island: 'Xybryle Island',
				flyable: false,
				surfable: false,
				fishable: false,
				divable: false,
				gym: false,
				rival: false,
				sidequests: false,
				revHQ: false,
				numRequiredJobs: 2,
				numRequiredBadges: 3,
				ferry: false,
				accessTo: ['ton-kura_seabed', 'ton-kura_shrine'],
				wilds: true,
				trainers: true,
				weather: '',
				wthrChance: 0,
				shops: [],
			},
		);

		await updatelocation(client,
			{
				loc: 'Ton-Kura Shrine',
				simpLoc: 'ton-kura',
				altSimpLoc: '',
				simpArea: 'shrine',
				island: 'Xybryle Island',
				flyable: false,
				surfable: false,
				fishable: false,
				divable: false,
				gym: false,
				rival: false,
				sidequests: false,
				revHQ: false,
				numRequiredJobs: 6,
				numRequiredBadges: 5,
				ferry: false,
				accessTo: ['ton-kura_caves'],
				wilds: true,
				trainers: false,
				weather: '',
				wthrChance: 0,
				shops: [],
			},
		);

		await updatelocation(client,
			{
				loc: 'Route NL15',
				simpLoc: 'routenl15',
				altSimpLoc: '',
				simpArea: '',
				island: '',
				flyable: true,
				surfable: true,
				fishable: true,
				divable: true,
				gym: false,
				rival: false,
				sidequests: false,
				revHQ: false,
				numRequiredJobs: 0,
				numRequiredBadges: 0,
				ferry: false,
				accessTo: ['routenl14', 'routenl16'],
				wilds: true,
				trainers: true,
				weather: '',
				wthrChance: 0,
				shops: [],
			},
		);

		await updatelocation(client,
			{
				loc: 'Route NL16',
				simpLoc: 'routenl16',
				altSimpLoc: '',
				simpArea: '',
				island: 'Krtuso Island',
				flyable: true,
				surfable: false,
				fishable: false,
				divable: false,
				gym: false,
				rival: false,
				sidequests: true,
				revHQ: false,
				numRequiredJobs: 0,
				numRequiredBadges: 0,
				ferry: true,
				accessTo: ['routenl15', 'versorectocity'],
				wilds: true,
				trainers: true,
				weather: '',
				wthrChance: 0,
				shops: [],
			},
		);

		await updatelocation(client,
			{
				loc: 'Versorecto City',
				simpLoc: 'versorectocity',
				altSimpLoc: '',
				simpArea: '',
				island: 'Krtuso Island',
				flyable: true,
				surfable: false,
				fishable: false,
				divable: false,
				gym: true,
				rival: false,
				sidequests: true,
				revHQ: false,
				numRequiredJobs: 0,
				numRequiredBadges: 0,
				ferry: false,
				accessTo: ['routenl16', 'routenl17'],
				wilds: false,
				trainers: true,
				weather: '',
				wthrChance: 0,
				shops: ['PokéMart', 'Versorecto Department Store'],
			},
		);

		await updatelocation(client,
			{
				loc: 'Route NL17',
				simpLoc: 'routenl17',
				altSimpLoc: '',
				simpArea: '',
				island: 'Krtuso Island',
				flyable: true,
				surfable: false,
				fishable: false,
				divable: false,
				gym: false,
				rival: false,
				sidequests: true,
				revHQ: false,
				numRequiredJobs: 0,
				numRequiredBadges: 0,
				ferry: false,
				accessTo: ['versorectocity', 'etaoincity'],
				wilds: true,
				trainers: true,
				weather: '',
				wthrChance: 0,
				shops: [],
			},
		);

		await updatelocation(client,
			{
				loc: 'Etaoin City',
				simpLoc: 'etaoincity',
				altSimpLoc: '',
				simpArea: '',
				island: 'Krtuso Island',
				flyable: true,
				surfable: false,
				fishable: false,
				divable: false,
				gym: false,
				rival: true,
				sidequests: false,
				revHQ: true,
				numRequiredJobs: 0,
				numRequiredBadges: 0,
				ferry: false,
				accessTo: ['routenl17', 'routenl18'],
				wilds: false,
				trainers: true,
				weather: 'Harsh Sunlight',
				wthrChance: 100,
				shops: ['PokéMart'],
			},
		);

		await updatelocation(client,
			{
				loc: 'Route NL18',
				simpLoc: 'routenl18',
				altSimpLoc: '',
				simpArea: '',
				island: 'Krtuso Island',
				flyable: true,
				surfable: false,
				fishable: false,
				divable: false,
				gym: false,
				rival: false,
				sidequests: false,
				revHQ: false,
				numRequiredJobs: 0,
				numRequiredBadges: 0,
				ferry: false,
				accessTo: ['etaoincity', 'jarovesubadlands_flatlands'],
				wilds: true,
				trainers: true,
				weather: 'Harsh Sunlight',
				wthrChance: 100,
				shops: [],
			},
		);

		await updatelocation(client,
			{
				loc: 'Jarovesu Badlands Flatlands',
				simpLoc: 'jarovesubadlands',
				altSimpLoc: '',
				simpArea: 'flatlands',
				island: 'Krtuso Island',
				flyable: true,
				surfable: false,
				fishable: false,
				divable: false,
				gym: false,
				rival: false,
				sidequests: true,
				revHQ: false,
				numRequiredJobs: 0,
				numRequiredBadges: 0,
				ferry: false,
				accessTo: ['routenl18', 'routenl19', 'jarovesubadlands_heights'],
				wilds: true,
				trainers: true,
				weather: 'Harsh Sunlight',
				wthrChance: 100,
				shops: [],
			},
		);

		await updatelocation(client,
			{
				loc: 'Jarovesu Badlands Heights',
				simpLoc: 'jarovesubadlands',
				altSimpLoc: '',
				simpArea: 'heights',
				island: 'Krtuso Island',
				flyable: true,
				surfable: false,
				fishable: false,
				divable: false,
				gym: false,
				rival: false,
				sidequests: false,
				revHQ: false,
				numRequiredJobs: 2,
				numRequiredBadges: 3,
				ferry: false,
				accessTo: ['jarovesubadlands_flatlands', 'jarovesubadlands_shrine'],
				wilds: true,
				trainers: true,
				weather: 'Harsh Sunlight',
				wthrChance: 100,
				shops: [],
			},
		);

		await updatelocation(client,
			{
				loc: 'Jarovesu Badlands Shrine',
				simpLoc: 'jarovesubadlands',
				altSimpLoc: '',
				simpArea: 'shrine',
				island: 'Krtuso Island',
				flyable: false,
				surfable: false,
				fishable: false,
				divable: false,
				gym: false,
				rival: false,
				sidequests: false,
				revHQ: false,
				numRequiredJobs: 6,
				numRequiredBadges: 5,
				ferry: false,
				accessTo: ['jarovesubadlands_heights'],
				wilds: true,
				trainers: false,
				weather: '',
				wthrChance: 0,
				shops: [],
			},
		);

		await updatelocation(client,
			{
				loc: 'Route NL19',
				simpLoc: 'routenl19',
				altSimpLoc: '',
				simpArea: '',
				island: 'Krtuso Island',
				flyable: true,
				surfable: false,
				fishable: false,
				divable: false,
				gym: false,
				rival: false,
				sidequests: false,
				revHQ: false,
				numRequiredJobs: 0,
				numRequiredBadges: 0,
				ferry: false,
				accessTo: ['jarovesubadlands_flatlands', 'fracturacity'],
				wilds: true,
				trainers: true,
				weather: 'Harsh Sunlight',
				wthrChance: 100,
				shops: [],
			},
		);

		await updatelocation(client,
			{
				loc: 'Fractura City',
				simpLoc: 'fracturacity',
				altSimpLoc: '',
				simpArea: '',
				island: 'Krtuso Island',
				flyable: true,
				surfable: false,
				fishable: false,
				divable: false,
				gym: true,
				rival: false,
				sidequests: true,
				revHQ: true,
				numRequiredJobs: 0,
				numRequiredBadges: 0,
				ferry: true,
				accessTo: ['routenl19', 'routenl20'],
				wilds: false,
				trainers: true,
				weather: '',
				wthrChance: 0,
				shops: ['PokéMart'],
			},
		);

		await updatelocation(client,
			{
				loc: 'Route NL20',
				simpLoc: 'routenl20',
				altSimpLoc: '',
				simpArea: '',
				island: '',
				flyable: true,
				surfable: true,
				fishable: true,
				divable: true,
				gym: false,
				rival: false,
				sidequests: false,
				revHQ: false,
				numRequiredJobs: 0,
				numRequiredBadges: 0,
				ferry: false,
				accessTo: ['fracturacity', 'leddintown'],
				wilds: true,
				trainers: true,
				weather: '',
				wthrChance: 0,
				shops: [],
			},
		);

		await updatelocation(client,
			{
				loc: 'Route NL21',
				simpLoc: 'routenl21',
				altSimpLoc: '',
				simpArea: '',
				island: '',
				flyable: true,
				surfable: true,
				fishable: true,
				divable: true,
				gym: false,
				rival: false,
				sidequests: false,
				revHQ: false,
				numRequiredJobs: 0,
				numRequiredBadges: 8,
				ferry: false,
				accessTo: ['routenl12/falantrdocks', 'alnirazruins/victoryroad_streets'],
				wilds: true,
				trainers: true,
				weather: '',
				wthrChance: 0,
				shops: [],
			},
		);

		await updatelocation(client,
			{
				loc: 'Alniraz Ruins / Victory Road Streets',
				simpLoc: 'alnirazruins',
				altSimpLoc: 'victoryroad',
				simpArea: 'streets',
				island: 'Adar Zilira',
				flyable: true,
				surfable: false,
				fishable: false,
				divable: false,
				gym: false,
				rival: true,
				sidequests: false,
				revHQ: false,
				numRequiredJobs: 0,
				numRequiredBadges: 8,
				ferry: false,
				accessTo: ['routenl21', 'alnirazruins/victoryroad_buildings', 'pokemonleaguehq'],
				wilds: true,
				trainers: true,
				weather: '',
				wthrChance: 0,
				shops: [],
			},
		);

		await updatelocation(client,
			{
				loc: 'Alniraz Ruins / Victory Road Buildings',
				simpLoc: 'alnirazruins',
				altSimpLoc: 'victoryroad',
				simpArea: 'buildings',
				island: 'Adar Zilira',
				flyable: true,
				surfable: false,
				fishable: false,
				divable: false,
				gym: false,
				rival: false,
				sidequests: false,
				revHQ: false,
				numRequiredJobs: 2,
				numRequiredBadges: 8,
				ferry: false,
				accessTo: ['alnirazruins/victoryroad_streets', 'alnirazruins/victoryroad_shrine'],
				wilds: true,
				trainers: true,
				weather: '',
				wthrChance: 0,
				shops: [],
			},
		);

		await updatelocation(client,
			{
				loc: 'Alniraz Ruins / Victory Road Shrine',
				simpLoc: 'alnirazruins',
				altSimpLoc: 'victoryroad',
				simpArea: 'shrine',
				island: 'Adar Zilira',
				flyable: false,
				surfable: false,
				fishable: false,
				divable: false,
				gym: false,
				rival: false,
				sidequests: false,
				revHQ: false,
				numRequiredJobs: 6,
				numRequiredBadges: 8,
				ferry: false,
				accessTo: ['alnirazruins/victoryroad_buildings'],
				wilds: true,
				trainers: false,
				weather: '',
				wthrChance: 0,
				shops: [],
			},
		);

		await updatelocation(client,
			{
				loc: 'Pokémon League Headquarters',
				simpLoc: 'pokemonleaguehq',
				altSimpLoc: '',
				simpArea: '',
				island: 'Adar Zilira',
				flyable: true,
				surfable: false,
				fishable: false,
				divable: false,
				gym: false,
				rival: false,
				sidequests: false,
				revHQ: false,
				numRequiredJobs: 0,
				numRequiredBadges: 8,
				ferry: false,
				accessTo: ['alnirazruins/victoryroad_streets'],
				wilds: false,
				trainers: false,
				weather: '',
				wthrChance: 0,
				shops: [],
			},
		);


	}
	catch (e) {
		console.error(e);
	}
	finally {
		await client.close();
	}
}

main().catch(console.error);

async function updatelocation(client, location) {
	const result = await client.db('turqdb').collection('locations').updateOne(
		{ loc: location.loc },
		{ $set: location },
		{ upsert: true },
	);

	console.log(`${result.matchedCount} document(s) matched the query criteria.`);
	console.log(`${result.modifiedCount} document(s) was/were updated.`);
}